/**
 * PDF Template Service
 * Builds HTML/CSS for Anvil PDF generation of EOR cost quotes
 */

function formatAmount(minorUnits, currency = 'NPR') {
  const major = minorUnits / 100
  return `${currency} ${major.toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`
}

function formatRate(rate) {
  return `${(parseFloat(rate) * 100).toFixed(0)}%`
}

function formatDate(dateStr) {
  if (!dateStr) return '—'
  return new Date(dateStr).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric'
  })
}

function capitalizeWords(str) {
  if (!str) return '—'
  return escapeHtml(str.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()))
}

function escapeHtml(str) {
  if (!str) return ''
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

/**
 * Build the HTML content for a quote PDF
 * @param {Object} quote - The quote record from eor_quotes table
 * @param {Object} organization - The organization record
 * @param {Object} generatedByUser - The user who generated the quote
 * @returns {{ html: string, css: string }}
 */
export function buildQuoteHtml(quote, organization, generatedByUser) {
  const employeeName = escapeHtml(
    [quote.employee_first_name, quote.employee_last_name].filter(Boolean).join(' ') || quote.employee_email
  )

  const generatedByName = escapeHtml(generatedByUser?.full_name || generatedByUser?.email || '—')
  const orgName = escapeHtml(organization?.name || '—')
  const quoteDate = formatDate(quote.created_at)
  const validUntil = formatDate(quote.valid_until)
  const startDate = formatDate(quote.start_date)

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
</head>
<body>
  <div class="page">
    <!-- Header -->
    <div class="header">
      <div class="brand">
        <div class="brand-name">TALYN</div>
        <div class="brand-tagline">Workforce Management</div>
      </div>
      <div class="quote-meta">
        <div class="quote-title">EOR Cost Quote</div>
        <table class="meta-table">
          <tr>
            <td class="meta-label">Quote #</td>
            <td class="meta-value">${quote.quote_number}</td>
          </tr>
          <tr>
            <td class="meta-label">Date</td>
            <td class="meta-value">${quoteDate}</td>
          </tr>
          <tr>
            <td class="meta-label">Valid Until</td>
            <td class="meta-value">${validUntil}</td>
          </tr>
        </table>
      </div>
    </div>

    <div class="divider"></div>

    <!-- Prepared For -->
    <div class="section">
      <div class="section-row">
        <div class="prepared-for">
          <div class="label">Prepared for</div>
          <div class="org-name">${orgName}</div>
          <div class="sub-text">Generated by: ${generatedByName}</div>
        </div>
      </div>
    </div>

    <div class="divider"></div>

    <!-- Employee Details -->
    <div class="section">
      <div class="section-header">Employee Details</div>
      <table class="details-table">
        <tr>
          <td class="detail-label">Name</td>
          <td class="detail-value">${employeeName}</td>
          <td class="detail-label">Email</td>
          <td class="detail-value">${escapeHtml(quote.employee_email)}</td>
        </tr>
        <tr>
          <td class="detail-label">Role</td>
          <td class="detail-value">${escapeHtml(quote.job_title) || '—'}</td>
          <td class="detail-label">Department</td>
          <td class="detail-value">${escapeHtml(quote.department) || '—'}</td>
        </tr>
        <tr>
          <td class="detail-label">Type</td>
          <td class="detail-value">${capitalizeWords(quote.employment_type)}</td>
          <td class="detail-label">Start Date</td>
          <td class="detail-value">${startDate}</td>
        </tr>
        <tr>
          <td class="detail-label">Pay Frequency</td>
          <td class="detail-value">${capitalizeWords(quote.pay_frequency)}</td>
          <td class="detail-label">Country</td>
          <td class="detail-value">Nepal (${quote.country_code || 'NPL'})</td>
        </tr>
      </table>
    </div>

    <!-- Monthly Cost Breakdown -->
    <div class="section">
      <div class="section-header accent">Monthly Employer Cost Breakdown</div>
      <table class="cost-table">
        <thead>
          <tr>
            <th class="cost-item-header">Item</th>
            <th class="cost-amount-header">Amount</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="cost-item">Employee Gross Salary</td>
            <td class="cost-amount">${formatAmount(quote.monthly_gross_salary, quote.salary_currency)}</td>
          </tr>
          <tr>
            <td class="cost-item">Employer SSF Contribution (${formatRate(quote.employer_ssf_rate)})</td>
            <td class="cost-amount">${formatAmount(quote.employer_ssf_amount, quote.salary_currency)}</td>
          </tr>
          <tr class="subtotal-row">
            <td class="cost-item"><strong>Subtotal (Local Currency)</strong></td>
            <td class="cost-amount"><strong>${formatAmount(quote.total_monthly_cost_local, quote.salary_currency)}</strong></td>
          </tr>
          <tr>
            <td class="cost-item">Talyn Platform Fee</td>
            <td class="cost-amount">${formatAmount(quote.platform_fee_amount, quote.platform_fee_currency)} /mo</td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Employee Reference -->
    <div class="section">
      <div class="section-header muted">Reference: Employee Deductions</div>
      <table class="cost-table reference-table">
        <tbody>
          <tr>
            <td class="cost-item">Employee SSF Deduction (${formatRate(quote.employee_ssf_rate)})</td>
            <td class="cost-amount">${formatAmount(quote.employee_ssf_amount, quote.salary_currency)}</td>
          </tr>
          <tr>
            <td class="cost-item">Est. Net Salary (before income tax)</td>
            <td class="cost-amount">${formatAmount(quote.estimated_net_salary, quote.salary_currency)}</td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Annual Estimate -->
    <div class="annual-box">
      <div class="annual-row">
        <div class="annual-item">
          <div class="annual-label">Annual Estimate (Local)</div>
          <div class="annual-value">${formatAmount(quote.total_annual_cost_local, quote.salary_currency)}</div>
        </div>
        <div class="annual-item right">
          <div class="annual-label">Annual Platform Fee</div>
          <div class="annual-value">${formatAmount(quote.platform_fee_amount * 12, quote.platform_fee_currency)}</div>
        </div>
      </div>
    </div>

    <!-- Footer -->
    <div class="footer">
      <div class="disclaimer">
        This quote is valid for 30 days from the date of issue. Rates are based on current
        Nepal Social Security Fund (SSF) regulations under the Social Security Act 2018.
        Actual costs may vary based on regulatory changes. This quote does not constitute
        a binding contract.
      </div>
      <div class="footer-brand">
        Talyn &middot; talynx.org &middot; support@talynx.org
      </div>
    </div>
  </div>
</body>
</html>`

  const css = `
    @page {
      size: A4;
      margin: 0;
    }

    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
      font-size: 13px;
      color: #1e293b;
      line-height: 1.5;
      background: #ffffff;
    }

    .page {
      padding: 48px 52px;
      max-width: 800px;
      margin: 0 auto;
    }

    /* Header */
    .header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      margin-bottom: 24px;
    }

    .brand-name {
      font-size: 28px;
      font-weight: 800;
      color: #4f46e5;
      letter-spacing: 3px;
    }

    .brand-tagline {
      font-size: 11px;
      color: #64748b;
      letter-spacing: 1px;
      margin-top: 2px;
    }

    .quote-meta {
      text-align: right;
    }

    .quote-title {
      font-size: 18px;
      font-weight: 700;
      color: #1e293b;
      margin-bottom: 8px;
    }

    .meta-table {
      border-collapse: collapse;
    }

    .meta-table td {
      padding: 1px 0;
      font-size: 12px;
    }

    .meta-label {
      color: #64748b;
      padding-right: 12px;
      text-align: right;
    }

    .meta-value {
      color: #1e293b;
      font-weight: 600;
      text-align: right;
    }

    /* Divider */
    .divider {
      height: 1px;
      background: #e2e8f0;
      margin: 16px 0;
    }

    /* Sections */
    .section {
      margin-bottom: 20px;
    }

    .section-row {
      display: flex;
      justify-content: space-between;
    }

    .section-header {
      font-size: 13px;
      font-weight: 700;
      color: #1e293b;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      margin-bottom: 10px;
      padding-bottom: 6px;
      border-bottom: 2px solid #e2e8f0;
    }

    .section-header.accent {
      border-bottom-color: #4f46e5;
    }

    .section-header.muted {
      color: #64748b;
      border-bottom-color: #e2e8f0;
    }

    /* Prepared For */
    .label {
      font-size: 11px;
      color: #64748b;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      margin-bottom: 4px;
    }

    .org-name {
      font-size: 18px;
      font-weight: 700;
      color: #1e293b;
    }

    .sub-text {
      font-size: 12px;
      color: #64748b;
      margin-top: 2px;
    }

    /* Details Table */
    .details-table {
      width: 100%;
      border-collapse: collapse;
    }

    .details-table td {
      padding: 5px 8px;
      font-size: 12px;
      vertical-align: top;
    }

    .detail-label {
      color: #64748b;
      width: 15%;
      font-weight: 500;
    }

    .detail-value {
      color: #1e293b;
      width: 35%;
      font-weight: 600;
    }

    /* Cost Tables */
    .cost-table {
      width: 100%;
      border-collapse: collapse;
      border: 1px solid #e2e8f0;
      border-radius: 6px;
      overflow: hidden;
    }

    .cost-table thead tr {
      background: #4f46e5;
    }

    .cost-item-header,
    .cost-amount-header {
      padding: 8px 16px;
      font-size: 11px;
      font-weight: 700;
      color: #ffffff;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }

    .cost-amount-header {
      text-align: right;
    }

    .cost-table tbody tr {
      border-bottom: 1px solid #e2e8f0;
    }

    .cost-table tbody tr:nth-child(even) {
      background: #f8fafc;
    }

    .cost-item {
      padding: 10px 16px;
      color: #475569;
    }

    .cost-amount {
      padding: 10px 16px;
      text-align: right;
      font-weight: 600;
      color: #1e293b;
    }

    .subtotal-row {
      background: #f1f5f9 !important;
    }

    .subtotal-row .cost-item,
    .subtotal-row .cost-amount {
      color: #1e293b;
    }

    /* Reference table (lighter styling) */
    .reference-table {
      border-color: #e2e8f0;
    }

    .reference-table .cost-item {
      color: #64748b;
    }

    .reference-table .cost-amount {
      color: #475569;
    }

    /* Annual Box */
    .annual-box {
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      padding: 20px 24px;
      margin: 24px 0;
    }

    .annual-row {
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    .annual-item.right {
      text-align: right;
    }

    .annual-label {
      font-size: 11px;
      color: #64748b;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      margin-bottom: 4px;
    }

    .annual-value {
      font-size: 22px;
      font-weight: 800;
      color: #1e293b;
    }

    /* Footer */
    .footer {
      margin-top: 40px;
      padding-top: 16px;
      border-top: 1px solid #e2e8f0;
    }

    .disclaimer {
      font-size: 10px;
      color: #94a3b8;
      line-height: 1.6;
      margin-bottom: 12px;
    }

    .footer-brand {
      font-size: 11px;
      color: #4f46e5;
      font-weight: 600;
      text-align: center;
      letter-spacing: 0.5px;
    }
  `

  return { html, css }
}

/**
 * Format USD cents as dollar string
 */
function formatUsd(cents) {
  const dollars = cents / 100
  return `$${dollars.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}

/**
 * Build the HTML content for a billing invoice PDF
 * @param {Object} invoice - The invoice record with line_items JSONB
 * @param {Object} organization - The organization record
 * @returns {{ html: string, css: string }}
 */
export function buildInvoiceHtml(invoice, organization) {
  const orgName = escapeHtml(organization?.name || '—')
  const orgAddress = [
    organization?.address_line1,
    organization?.address_line2,
    [organization?.city, organization?.state, organization?.postal_code].filter(Boolean).join(', '),
    organization?.country
  ].filter(Boolean).map(escapeHtml).join('<br>')
  const billingEmail = escapeHtml(organization?.billing_email || organization?.email || '—')

  const issueDate = formatDate(invoice.issue_date)
  const dueDate = formatDate(invoice.due_date)
  const billingPeriod = `${formatDate(invoice.billing_period_start)} — ${formatDate(invoice.billing_period_end)}`

  const lineItems = invoice.line_items || []
  const config = invoice.config_snapshot || {}
  const exchangeRate = parseFloat(invoice.exchange_rate) || 0
  const rateDisplay = exchangeRate > 0 ? `1 NPR = $${exchangeRate.toFixed(4)} USD` : '—'

  // Build line items rows
  const lineItemRows = lineItems.map((item, i) => `
    <tr class="${i % 2 === 1 ? 'alt-row' : ''}">
      <td class="cell">${escapeHtml(item.member_name)}</td>
      <td class="cell">${escapeHtml(item.job_title || '—')}</td>
      <td class="cell right">${formatAmount(item.monthly_gross_local, item.salary_currency || 'NPR')}</td>
      <td class="cell right">${formatAmount(item.employer_ssf_local, item.salary_currency || 'NPR')}</td>
      <td class="cell right">${formatAmount(item.total_cost_local, item.salary_currency || 'NPR')}</td>
      <td class="cell right">${formatUsd(item.cost_usd_cents)}</td>
      <td class="cell right">${formatUsd(item.platform_fee_cents)}</td>
    </tr>
  `).join('')

  const subtotalLocalCents = invoice.subtotal_local_cents || 0
  const subtotalUsdCents = lineItems.reduce((sum, item) => sum + (item.cost_usd_cents || 0), 0)
  const platformFeeCents = invoice.platform_fee_cents || 0
  const totalAmountCents = invoice.total_amount_cents || 0

  const html = `
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body>
  <div class="page">
    <!-- Header -->
    <div class="header">
      <div class="brand">
        <div class="brand-name">TALYN</div>
        <div class="brand-tagline">Workforce Management</div>
      </div>
      <div class="invoice-meta">
        <div class="invoice-title">INVOICE</div>
        <table class="meta-table">
          <tr><td class="meta-label">Invoice #</td><td class="meta-value">${escapeHtml(invoice.invoice_number)}</td></tr>
          <tr><td class="meta-label">Issue Date</td><td class="meta-value">${issueDate}</td></tr>
          <tr><td class="meta-label">Due Date</td><td class="meta-value due-date">${dueDate}</td></tr>
          <tr><td class="meta-label">Billing Period</td><td class="meta-value">${billingPeriod}</td></tr>
        </table>
      </div>
    </div>

    <div class="divider"></div>

    <!-- Bill To -->
    <div class="section">
      <div class="section-row">
        <div class="bill-to">
          <div class="label">BILL TO</div>
          <div class="org-name">${orgName}</div>
          <div class="address">${orgAddress}</div>
          <div class="sub-text">${billingEmail}</div>
        </div>
        <div class="bill-from">
          <div class="label">FROM</div>
          <div class="org-name">Talyn Inc.</div>
          <div class="sub-text">support@talynx.org</div>
        </div>
      </div>
    </div>

    <div class="divider"></div>

    <!-- Employee Line Items -->
    <div class="section">
      <div class="section-header accent">Employee Cost Breakdown (${lineItems.length} employee${lineItems.length !== 1 ? 's' : ''})</div>
      <div class="rate-note">Exchange Rate: ${rateDisplay}</div>
      <table class="inv-table">
        <thead>
          <tr>
            <th class="th">Employee</th>
            <th class="th">Role</th>
            <th class="th right">Gross (NPR)</th>
            <th class="th right">SSF ${formatRate(config.employer_ssf_rate || 0)}</th>
            <th class="th right">Cost (NPR)</th>
            <th class="th right">Cost (USD)</th>
            <th class="th right">Platform Fee</th>
          </tr>
        </thead>
        <tbody>
          ${lineItemRows}
        </tbody>
      </table>
    </div>

    <!-- Totals -->
    <div class="totals-box">
      <table class="totals-table">
        <tr>
          <td class="total-label">Local Currency Subtotal</td>
          <td class="total-value">${formatAmount(subtotalLocalCents, 'NPR')}</td>
        </tr>
        <tr>
          <td class="total-label">USD Conversion (@ ${rateDisplay})</td>
          <td class="total-value">${formatUsd(subtotalUsdCents)}</td>
        </tr>
        <tr>
          <td class="total-label">Platform Fees (${lineItems.length} x ${formatUsd(config.platform_fee_amount || 0)}/mo)</td>
          <td class="total-value">${formatUsd(platformFeeCents)}</td>
        </tr>
        <tr class="grand-total-row">
          <td class="total-label"><strong>TOTAL DUE (USD)</strong></td>
          <td class="total-value grand-total"><strong>${formatUsd(totalAmountCents)}</strong></td>
        </tr>
      </table>
    </div>

    <!-- Payment Terms -->
    <div class="section">
      <div class="payment-terms">
        <strong>Payment Terms:</strong> Payment is due by ${dueDate}. For automatic payment accounts,
        funds will be collected via ACH from your linked bank account. For manual payment accounts,
        please remit payment via wire transfer to Talyn's US bank account.
      </div>
    </div>

    <!-- Footer -->
    <div class="footer">
      <div class="disclaimer">
        This invoice is generated based on active employees during the billing period.
        Rates are based on Nepal Social Security Fund (SSF) regulations under the Social Security Act 2018.
        Exchange rates are set by Talyn administration and may differ from market rates.
      </div>
      <div class="footer-brand">
        Talyn &middot; talynx.org &middot; support@talynx.org
      </div>
    </div>
  </div>
</body>
</html>`

  const css = buildInvoiceCss()
  return { html, css }
}

/**
 * Build the HTML content for a payment receipt PDF
 */
export function buildReceiptHtml(invoice, organization, paymentDate) {
  const orgName = escapeHtml(organization?.name || '—')
  const billingEmail = escapeHtml(organization?.billing_email || organization?.email || '—')
  const paidDate = formatDate(paymentDate || invoice.paid_at)
  const billingPeriod = `${formatDate(invoice.billing_period_start)} — ${formatDate(invoice.billing_period_end)}`
  const lineItems = invoice.line_items || []
  const totalAmountCents = invoice.total_amount_cents || 0

  const html = `
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body>
  <div class="page">
    <!-- Header -->
    <div class="header">
      <div class="brand">
        <div class="brand-name">TALYN</div>
        <div class="brand-tagline">Workforce Management</div>
      </div>
      <div class="invoice-meta">
        <div class="receipt-title">PAYMENT RECEIPT</div>
        <table class="meta-table">
          <tr><td class="meta-label">Invoice #</td><td class="meta-value">${escapeHtml(invoice.invoice_number)}</td></tr>
          <tr><td class="meta-label">Payment Date</td><td class="meta-value">${paidDate}</td></tr>
          <tr><td class="meta-label">Billing Period</td><td class="meta-value">${billingPeriod}</td></tr>
        </table>
      </div>
    </div>

    <div class="divider"></div>

    <!-- Paid stamp -->
    <div class="paid-badge">PAID</div>

    <!-- Receipt Details -->
    <div class="section">
      <div class="section-row">
        <div class="bill-to">
          <div class="label">RECEIVED FROM</div>
          <div class="org-name">${orgName}</div>
          <div class="sub-text">${billingEmail}</div>
        </div>
      </div>
    </div>

    <div class="divider"></div>

    <!-- Summary -->
    <div class="section">
      <div class="section-header accent">Payment Summary</div>
      <table class="totals-table">
        <tr>
          <td class="total-label">Employees Covered</td>
          <td class="total-value">${invoice.employee_count || lineItems.length}</td>
        </tr>
        <tr>
          <td class="total-label">Local Salary Costs (USD)</td>
          <td class="total-value">${formatUsd(lineItems.reduce((s, i) => s + (i.cost_usd_cents || 0), 0))}</td>
        </tr>
        <tr>
          <td class="total-label">Platform Fees</td>
          <td class="total-value">${formatUsd(invoice.platform_fee_cents || 0)}</td>
        </tr>
        <tr class="grand-total-row">
          <td class="total-label"><strong>TOTAL PAID</strong></td>
          <td class="total-value grand-total"><strong>${formatUsd(totalAmountCents)}</strong></td>
        </tr>
      </table>
    </div>

    <!-- Footer -->
    <div class="footer">
      <div class="disclaimer">
        This receipt confirms payment for the above invoice. Please retain for your records.
      </div>
      <div class="footer-brand">
        Talyn &middot; talynx.org &middot; support@talynx.org
      </div>
    </div>
  </div>
</body>
</html>`

  const css = buildInvoiceCss()
  return { html, css }
}

/**
 * Shared CSS for invoice and receipt PDFs
 */
function buildInvoiceCss() {
  return `
    @page { size: A4; margin: 0; }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 13px; color: #1e293b; line-height: 1.5; background: #fff; }
    .page { padding: 48px 52px; max-width: 800px; margin: 0 auto; }

    .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 24px; }
    .brand-name { font-size: 28px; font-weight: 800; color: #4f46e5; letter-spacing: 3px; }
    .brand-tagline { font-size: 11px; color: #64748b; letter-spacing: 1px; margin-top: 2px; }
    .invoice-meta { text-align: right; }
    .invoice-title, .receipt-title { font-size: 22px; font-weight: 800; color: #1e293b; margin-bottom: 8px; letter-spacing: 2px; }
    .receipt-title { color: #059669; }
    .meta-table { border-collapse: collapse; }
    .meta-table td { padding: 1px 0; font-size: 12px; }
    .meta-label { color: #64748b; padding-right: 12px; text-align: right; }
    .meta-value { color: #1e293b; font-weight: 600; text-align: right; }
    .due-date { color: #dc2626; }

    .divider { height: 1px; background: #e2e8f0; margin: 16px 0; }
    .section { margin-bottom: 20px; }
    .section-row { display: flex; justify-content: space-between; }
    .section-header { font-size: 13px; font-weight: 700; color: #1e293b; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 10px; padding-bottom: 6px; border-bottom: 2px solid #e2e8f0; }
    .section-header.accent { border-bottom-color: #4f46e5; }

    .label { font-size: 11px; color: #64748b; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 4px; }
    .org-name { font-size: 18px; font-weight: 700; color: #1e293b; }
    .address { font-size: 12px; color: #475569; margin-top: 4px; line-height: 1.6; }
    .sub-text { font-size: 12px; color: #64748b; margin-top: 2px; }
    .rate-note { font-size: 11px; color: #64748b; margin-bottom: 8px; }

    .inv-table { width: 100%; border-collapse: collapse; border: 1px solid #e2e8f0; font-size: 11px; }
    .th { padding: 8px 10px; background: #4f46e5; color: #fff; font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px; font-size: 10px; }
    .th.right { text-align: right; }
    .cell { padding: 8px 10px; border-bottom: 1px solid #e2e8f0; color: #475569; }
    .cell.right { text-align: right; font-weight: 600; color: #1e293b; }
    .alt-row { background: #f8fafc; }

    .totals-box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px 20px; margin: 20px 0; }
    .totals-table { width: 100%; border-collapse: collapse; }
    .totals-table tr { border-bottom: 1px solid #e2e8f0; }
    .totals-table tr:last-child { border-bottom: none; }
    .total-label { padding: 8px 0; color: #475569; font-size: 13px; }
    .total-value { padding: 8px 0; text-align: right; font-weight: 600; color: #1e293b; font-size: 13px; }
    .grand-total-row { background: #4f46e5; border-radius: 4px; }
    .grand-total-row .total-label { color: #fff; padding: 12px 8px; }
    .grand-total-row .total-value { color: #fff; padding: 12px 8px; font-size: 16px; }

    .paid-badge { display: inline-block; background: #059669; color: #fff; font-size: 18px; font-weight: 800; letter-spacing: 4px; padding: 8px 24px; border-radius: 4px; margin-bottom: 16px; }
    .payment-terms { font-size: 12px; color: #475569; background: #fffbeb; border: 1px solid #fde68a; border-radius: 6px; padding: 12px 16px; }

    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; }
    .disclaimer { font-size: 10px; color: #94a3b8; line-height: 1.6; margin-bottom: 12px; }
    .footer-brand { font-size: 11px; color: #4f46e5; font-weight: 600; text-align: center; letter-spacing: 0.5px; }
  `
}
